### ISSUE TITLE
Bibliography differes from requirements

### ISSUE THREAD

**Issue by dovydasvenckus** [LIKS/bachelor_thesis_template_vu_mif_se#3]
Hello, thank you for this great template.

I have noticed that bibliography differes from official requirements http://www.mif.vu.lt/katedros/se/Studentams/BAKALAURO%20BAIGIAMOJO%20DARBO%20STRUKTURA%202013.pdf . 

I'm latex novice so probably I won't be able to fix it and make pull request.

Would it be hard to fix it?

**Comment by niekas** [comment]
Sveiki, Doydai, įmanoma visiškai tiksliai atkartoti literatūros šaltinio stilių, tam reikėtų sukurti stiliaus .bst failą. Visigi, manau, kad tai nėra būtina. Nesu girdėjęs, kad kam nors kada nors būtų dėl to priekaištavę tiek vadovai, tiek gynimo metu. Dabar yra parinktas panašiausias iš oficialių bibliografijos stilių į pageidaujamą ir to turėtų pakakti. Jeigu įsitikinsite, kad literatūros šaltinių stilių reikia koreguoti, galėsiu tai padaryti, nors tai ir užtruktų.

**Comment by dovydasvenckus** [comment]
Na turbūt esat teisus dėl šito, nes mažai tikėtina, kad kažkas prisikabins prie tokių smulkmenų. Jei norit galit uždaryti šitą issue.
