### ISSUE TITLE
Bibliography does not appear in generated PDF

### ISSUE THREAD

**Issue by RimasR** [LIKS/bachelor_thesis_template_vu_mif_se#4]
Sveiki,

Pasileidžiant jūsų sukurtą bakalaurinio template'ą, nėra pateikiamas literatūros sąrašas. Latex'o kompiliavimui naudoju TexMaker. Bibliografijoje yra pateikti keli jūsų pavyzdžiai - ji nėra tuščia.

**Comment by niekas** [comment]
Sveikas, Rimai, 
šią problemą galima išspręsti pakeitus TexMaker nustatymus. Mano atveju (Ubuntu) tai galima padaryti TexMaker meniu juostoje pasirinkus Options -> Configure TexMaker ir atsidariusiame lange prie Bib(la)tex parinkties įvedus "biber %". Tada kompiliuojant pasirinkti "XeLaTex", "Biber", "XeLaTeX". 
Tikiuosi tai padės.

**Comment by RimasR** [comment]
Ačiū, suveikė kaip priklauso 👍
